### ISSUE TITLE
Error in makeControl instructions in WIki and filename.

### ISSUE THREAD

**Issue by carmensandoval** [hemberg-lab/D3E#1]
There seems to be an error in the wiki for making the control file, as well as in the file name for the .py script.

A control file can be created by using makeControl.py which has the following syntax:

`python makeControl inputFile outputFile label`

Hence in our case we run:

`python makeControl example.txt example_control.txt G1`

Should be:

`python D3EMakeControl.py inputFile outputFile label`

And the filename has a typo, it's missing the 'r' in Control.

Thanks!

**Comment by mhemberg** [comment]
Hi Carmen,

thanks for pointing out these errors. Unfortunately, Mihails who does all the coding is away this week but we will make sure to fix the problems asap (things will likely go terribly wrong if I try to fix them). In the meantime, I have updated the wiki.

Best,

Martin

**Comment by carmensandoval** [comment]
Thanks, Martin!

I believe the `D3ESplitData.py` and `D3EMergeOutput.py` are missing from the directory.

**Comment by mhemberg** [comment]
Apologies for the missing files. Unfortunately, I can only access the code which is available on github, so I will have to ask Mihails to upload the missing the files as soon as he is back.

Thanks again for your feedback!

**Comment by mdelmans** [comment]
D3ESplitData.py and D3EMergeOutput.py are uploaded now. Thank you for the comment.

**Comment by carmensandoval** [comment]
Thank you for the follow-up! I am looking forward to exploring our data using D3E.
